DROP TABLE IF EXISTS MOVIMIENTOS;
DROP TABLE IF EXISTS CUENTAS;
DROP TABLE IF EXISTS CLIENTES;
DROP TABLE IF EXISTS PERSONAS;
DROP SEQUENCE IF EXISTS MOVIMIENTOS_SEQ;
DROP SEQUENCE IF EXISTS CUENTAS_SEQ;

CREATE SEQUENCE CUENTAS_SEQ start 1 increment 1;
CREATE SEQUENCE MOVIMIENTOS_SEQ start 1 increment 1;

CREATE TABLE PERSONAS
(
    IDENTIFICACION VARCHAR(10) PRIMARY KEY,
    NOMBRE         VARCHAR(30) NOT NULL,
    GENERO         VARCHAR(1)  NOT NULL CHECK (GENERO IN ('M', 'F')),
    EDAD           SMALLINT    NOT NULL CHECK (EDAD > 0),
    DIRECCION      VARCHAR(30) NOT NULL,
    TELEFONO       VARCHAR(10) NOT NULL
);

CREATE TABLE CLIENTES
(
    IDENTIFICACION  VARCHAR(10) PRIMARY KEY,
    CLAVE           VARCHAR(30) NOT NULL,
    ESTADO          VARCHAR(3)  NOT NULL CHECK (ESTADO IN ('ACT', 'INA', 'BLO', 'SUS')),
    FOREIGN KEY (IDENTIFICACION) REFERENCES PERSONAS (IDENTIFICACION)
);

CREATE TABLE CUENTAS
(
    NUMERO_CUENTA   BIGINT          PRIMARY KEY DEFAULT NEXTVAL('CUENTAS_SEQ'),
    CLIENTE_ID      VARCHAR(10)     NOT NULL,
    TIPO            VARCHAR(3)      NOT NULL NOT NULL CHECK (TIPO IN ('AHO', 'CTE')),
    SALDO           DECIMAL(10, 2)  NOT NULL CHECK (SALDO >= 0),
    ESTADO          VARCHAR(3)      NOT NULL NOT NULL CHECK (ESTADO IN ('ACT', 'INA')),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (IDENTIFICACION)
);

CREATE TABLE MOVIMIENTOS
(
    ID              BIGINT          PRIMARY KEY DEFAULT NEXTVAL('MOVIMIENTOS_SEQ'),
    FECHA           TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NUMERO_CUENTA   BIGINT          NOT NULL,
    TIPO            VARCHAR(3)      NOT NULL NOT NULL CHECK (TIPO IN ('DEP', 'RET')),
    ESTADO          VARCHAR(3)      NOT NULL NOT NULL CHECK (ESTADO IN ('ACT', 'INA')),
    SALDO_INICIAL   DECIMAL(10, 2)  NOT NULL CHECK (SALDO_INICIAL >= 0),
    VALOR           DECIMAL(10, 2)  NOT NULL CHECK (VALOR >= 0),
    FOREIGN KEY (NUMERO_CUENTA) REFERENCES CUENTAS (NUMERO_CUENTA)
);

COMMIT;
